Add ability to read pytest output in a friendly way
Instead of all the irrelevant stuff like file paths, python versions etc from pytest you will now hear the test count, the error message and the line of code that triggered it e.g. "1 failed, 5 passed, AttributeError: 'NoneType' object has no attribute 'group', code is results = parse_output(lines)"